// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace animalshelterapi.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20221028190622_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 6,
                            Breed = "pit bull mix",
                            Color = "White",
                            IsFixed = true,
                            Name = "Titan",
                            Sex = "male",
                            Species = "canine"
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            Breed = "pit bull mix",
                            Color = "brown",
                            IsFixed = true,
                            Name = "Milo",
                            Sex = "male",
                            Species = "canine"
                        },
                        new
                        {
                            Id = 3,
                            Age = 4,
                            Breed = "Shepherd Mix",
                            Color = "Black",
                            IsFixed = true,
                            Name = "Korra",
                            Sex = "female",
                            Species = "canine"
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            Breed = "american shorthair",
                            Color = "black",
                            IsFixed = true,
                            Name = "Sid",
                            Sex = "male",
                            Species = "feline"
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            Breed = "mixed",
                            Color = "tabby",
                            IsFixed = true,
                            Name = "Maeve",
                            Sex = "female",
                            Species = "feline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
